default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sovia7
  #username: sovia
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: sovia7_test

production:
  <<: *default
  database: sovia7
  username: sovia
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
