test: &default
  client_id: <%= Rails.application.credentials.paypal.dig(:sandbox, :client_id) %>
  client_secret: <%= Rails.application.credentials.paypal.dig(:sandbox, :client_secret) %>
  mode: sandbox

development:
  <<: *default

production:
  <<: *default
#  mode: live
#  client_id: <%#= Rails.application.credentials.paypal.dig(:live, :client_id) %>
#  client_secret: <%#= Rails.application.credentials.paypal.dig(:live, :client_secret) %>
